language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  
cache: cargo